### ISSUE TITLE
SubmitFormUsingPOST is kinda broken

### ISSUE THREAD

**Issue by neclimdul** [neclimdul/marketo-rest#5]
This isn't really something easily fixable in this project. The documentation is actually incorrect causing the API to be a little hard to use and often broken.

https://developers.marketo.com/rest-api/endpoint-reference/lead-database-endpoint-reference/#!/Leads/SubmitFormUsingPOST

The problem is that the model doesn't take into account the [result level error codes](https://developers.marketo.com/rest-api/error-codes/#record_level_errors) which will lead to fatal errors on form submission errors. For example if there are changes to form fields and possibly some other causes.

**Comment by neclimdul** [comment]
As noted, there isn't much to fix ATM as this is a documentation problem on Marketo's side but documenting this as a known problem

**Comment by neclimdul** [comment]
It looks like the docs might have been updated and this could be fixed.

**Comment by chx** [comment]
I really have no idea what's going on. We tried to replace the old `leadCapture/save2` endpoint with this and this endpoint rejects -- unlike `forms2` -- anything that is not in the actual form. I suspect `save2` was also updating the lead while submitting the form but there is no documentation and no examples whatsoever.

**Comment by neclimdul** [comment]
There is not any useful documentation. its pretty frustrating. 

I've seen the same thing. The new system requires additional validation. I complained about this in a support request but they claimed that was the expected functionality and closed the ticket. Let me know if you have better lucky convincing them this is wrong because we've been training users that there's going to be a big change around this.

**Comment by neclimdul** [comment]
this is probably mostly functional but undocumented cases like 03b6695769321f6d3933780b6d9518445316ca06 keep cropping up so this will probably be a long process of capturing failures :( 

Going to close this since its "working" as designed the best I can tell ATM and will open issues for individual failures as needed in the appropriate queues.
